"""empty message

Revision ID: 060ee02f9f27
Revises: 3bcba07ee494
Create Date: 2021-12-10 14:30:35.690683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060ee02f9f27'
down_revision = '3bcba07ee494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
